### ISSUE TITLE
Add EPEL repo for armhfp

### ISSUE THREAD

**Issue by Cinux90** [while-true-do/ansible-role-repo-epel#12]
### Type of Report

Feature Request

### Actual behaviour

No EPEL Repo for armhfp architecture

### Expected behaviour

Install EPEL for armhfp architecture as described here:
[EPEL armfhp](https://wiki.centos.org/SpecialInterestGroup/AltArch/armhfp?action=show&redirect=SpecialInterestGroup%2FAltArch%2FArm32#head-2c416cfaecdf675f43a5be7a81ad50e81e640c93)

**Comment by donvipre** [comment]
looks like experimental stuff, should we really implement this?

**Comment by Cinux90** [comment]
Sure its a good point. However... I have create a pull request and add a Flag that must be set to confirm that you know that's experimental.

**Comment by donvipre** [comment]
ok, then we will implement this..
Further discussion then on the pull request
