### ISSUE TITLE
LICENSE file broken

### ISSUE THREAD

**Issue by donvipre** [while-true-do/ansible-role-repo-epel#3]
### Type of Report

bug

### Actual behaviour

license not parsed by github

### Expected behaviour

license should work with github

**Comment by keesvv** [comment]
The license can only be parsed if there is no extension, so instead of naming the license file `LICENSE.md`, call it `LICENSE` instead.

**Comment by daniel-schier** [comment]
additionally the header must be removed.
a working example is here:
https://github.com/while-true-do/ansible-galaxy-skeleton/blob/master/LICENSE
